version: '3.8'

services:
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    volumes:
      - ../apps/web:/app
      - /app/node_modules
    depends_on:
      - api
    command: pnpm dev

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ../apps/api:/app
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
