name: 'Build and Deploy to AWS Lambda'

on:
  push:
    branches: ['main']

permissions:
  id-token: write

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f apps/api/Dockerfile \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            apps/api
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG